importScripts(
  "../shared/browser-api.js",
  "../shared/currencies.js",
  "../shared/settings.js",
  "../shared/messages.js",
  "../shared/page-access.js",
  "../shared/content-script-resources.js",
  "http.js",
  "catalog-snapshot.js",
  "catalog.js",
  "rates.js",
  "rate-history.js",
  "site-preferences.js",
  "settings-service.js",
  "page-actions.js",
  "onboarding.js",
  "review-prompt.js",
  "main.js"
);
